export enum UsersConstants {
    GETALL_REQUEST = 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS = 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE = 'USERS_GETALL_FAILURE',

    REMOVE_REQUEST = 'USERS_REMOVE_REQUEST',
    REMOVE_SUCCESS = 'USERS_REMOVE_SUCCESS',
    REMOVE_FAILURE = 'USERS_REMOVE_FAILURE'    
}
