export enum UsersTableConstants {
    SELECT_ALL = 'USERS_TABLE_SELECT_ALL',
    SELECT_ONE = 'USERS_TABLE_SELECT_ONE',
    PAGE_CHANGE = 'USERS_TABLE_PAGE_CHANGE',
    ROWS_PER_PAGE_CHANGE = 'USERS_TABLE_ROWS_PER_PAGE_CHANGE',
};
